### ISSUE TITLE
this.driver.connect is not a function

### ISSUE THREAD

**Issue by lewatt23** [devsamir/electronjs-react-typeorm-boilerplate#1]
Hello @devsamir , thanks for this repo, but i have an issue is not related to this repo but i figured out that you could help me if you have encounter the same problem. actually when running my connection i have the following error `Unhandled Rejection (TypeError): this.driver.connect is not a function` from my research it seems like the error is related typeorm not been used to electron. do you have an idea on how to resolve that ?.

**Comment by devsamir** [comment]
the repository is still not perfect, there are some bugs that I still need
to fix, I also still can't use entity for the model, while I'm still using
raw query, about your problem, are you import typeorm without using
remote.require("typeorm") ? or you used class based ?

if it's not like that, try showing how the error is in more detail



Pada tanggal Jum, 9 Jul 2021 pukul 23.33 lewatt23 ***@***.***>
menulis:

**Comment by lewatt23** [comment]
hello  here a portion of my code, imported it one my screen to test
```
`import { remote } from "electron";
import Patient from "../../Database/models/Patient";
const { createConnection } = remote.require("typeorm");

const Home = () => {
  useEffect(() => {
    testDatabase();
  }, [0]);
  async function testDatabase() {
    createConnection({
      type: "mysql",
      host: "http://192.168.64.2",
      port: 8080,
      username: "stanly",
      password: "stanly",
      database: "electron",
    }).then((connection: any) => {
      let photo = new Patient();
      photo.name = "Me and Bears";
      photo.surname = "I am near polar bears";

      return connection.manager.save(photo).then((photo:any) => {
        console.log("Patien has been saved. Photo id is", photo.id);
      });
    });
  }`
```

**Comment by lewatt23** [comment]
am closing this issue, thanks for your help, i will recommend you to go with **electron-forge** it seems to solve all the problems of native node modules that electron has, and also solved my problem too.

**Comment by devsamir** [comment]
sorry i've been busy this couple days, i am glad you solve your problem
bro, thank you

Pada tanggal Min, 11 Jul 2021 pukul 03.24 lewatt23 ***@***.***>
menulis:
